Sunbird-Obsrv/sunbird-analytics-core

- analytics-core/pom.xml
- analytics-job-driver/pom.xml
- pom.xml
Upgrading spark to 2.4.4 from 2.0.1
Dependent PR : https://github.com/project-sunbird/sunbird-data-pipeline/pull/631/
> Spark Upgrade -2.4.4

- analytics-core/src/main/scala/org/ekstep/analytics/framework/DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/DataFilter.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/FrameworkContext.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/OutputDispatcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/DruidDataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/DatasetUtil.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/JSONUtils.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestDataFilter.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestFrameworkContext.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestOutputDispatcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/fetcher/TestDruidDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestCommonUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestRestUtil.scala
- analytics-job-driver/pom.xml
- analytics-job-driver/src/main/scala/org/ekstep/analytics/framework/driver/BatchJobDriver.scala
- analytics-job-driver/src/test/resources/application.conf
- analytics-job-driver/src/test/scala/org/ekstep/analytics/framework/TestJobDriver.scala
- analytics-job-driver/src/test/scala/org/ekstep/analytics/framework/TestJobDriver2.scala
Add/update test cases to get 100% coverage.
> Release 2.8.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/dispatcher/ScriptDispatcher.scala
@SanthoshVasabhaktula : Please review it
> #SB-17790 | User detail report zip generation fixes added

- auto_build_deploy
…ces whenever a new tag is created in the repo
> added jenkins file to automate build, artifactupload and deploy service

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/DatasetUtil.scala
- analytics-core/src/test/resources/report.csv
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestDatasetUtil.scala
> TG-907 : Code changes for zip exhaust file

- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/DruidDataFetcher.scala
> SC-00: Merge 3.7.0 to 3.8.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/MergeUtil.scala
- analytics-core/src/test/resources/application.conf
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestMergeUtil.scala
This changes include fix for the json file issue in merge script with table key and value mapping issue 
> TG-480: Fix the json format, key value table mapping issue

- analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/DatasetUtil.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/MergeUtil.scala
- analytics-core/src/test/resources/delta_order.csv
- analytics-core/src/test/resources/delta_rollup.csv
- analytics-core/src/test/resources/report_weekly.csv
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestDatasetUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestMergeUtil.scala
> Merge Release 3.8.1 to Release-3.9.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/MergeUtil.scala
This include fix for merge script issue for the non column order reports
> TG-967:Fix the ETB metrics model merge config issue

- analytics-core/src/test/resources/delta_rollup.csv
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestMergeUtil.scala
> Merge release-3.8.1 changes to 3.9.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/DatasetUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestDatasetUtil.scala
This  includes fix for zip functionality issue implementation change for cluster reports
> TG-965: Fix the zip cluster issue

- analytics-job-driver/src/main/scala/org/ekstep/analytics/framework/driver/BatchJobDriver.scala
> Issue #TG-1016 feat: Fix metric event job name for druid reports

- analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25480" title="SB-25480" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25480</a>  UCI - Conversation assessment data exhaust for States
</td></table>
<br />
> Issue #SB-25480 feat: Question case class changes to include type field

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/MergeUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25854" title="SB-25854" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25854</a>  Moving of all the druid jobs to HD Cluster
</td></table>
<br />
This includes fix to merge script logs while exception is thrown
> SB-25854: Fix the merge script logging

- analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/DruidDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/fetcher/TestDruidDataFetcher.scala
This PR has changes to Druid Fetcher Framework to create & execute SQL join queries.
> #TG-1029 feat: DruidDataFetcher enhancements to take SQL join queries

- analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/DruidDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/fetcher/TestDruidDataFetcher.scala
This changes includes fix for exhaust query to avoid timeouts
> Fix the exhaust query for timeout issues

- analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala
> Merge Release 4.1.0 changes to Release 4.2.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26355" title="SB-26355" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24793</a>  Data Correction Script 
</td></table>
<br />
Reading the write consistency config from the job config changes
> SB-26355 -  Adding cassandra write consistency level to the job.

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24793" title="SB-24793" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24793</a>  Assessments Archival - Jobs Implementation and testing
</td></table>
<br />
Reverts project-sunbird/sunbird-analytics-core#111
> SB-24793  - Revert  Release 4.1.0 into Release-4.2.0"

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24793" title="SB-24793" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24793</a>  Assessments Archival - Jobs Implementation and testing
</td></table>
<br />
Reverts project-sunbird/sunbird-analytics-core#112
> SB-24793  - Merge reverted changes into release-4.2.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala
> Issue #0000: Type change for extra in edata

- analytics-core/src/main/scala/org/ekstep/analytics/framework/Models.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24793" title="SB-24793" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24793</a>  Assessments Archival - Jobs Implementation and testing
</td></table>
<br />
> SB-24793 - Release 4.2.1 into Release-4.4.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/DruidDataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/fetcher/TestDruidDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestCommonUtil.scala
This PR has enhancements to roundDouble logic in framework to handle for BigDecimal type as it was getting converted to scientific notation like this **3.969513467E9**
> Issue #0000 fix: Fix round double issue for big decimal values in druid reports.

- analytics-core/pom.xml
> Issue #TG-1154 feat: Upgrade log4j version to 2.16.0

- .circleci/config.yml
- analytics-core/pom.xml
- analytics-job-driver/pom.xml
- pom.xml
> Issue #TG-1177 feat: Upgrade to Java 11 for Analytics Core

- .circleci/config.yml
- analytics-core/pom.xml
- analytics-job-driver/pom.xml
- pom.xml
Reverts project-sunbird/sunbird-analytics-core#126
> Revert "Issue #TG-1177 feat: Upgrade to Java 11 for Analytics Core"

- .circleci/config.yml
- analytics-core/pom.xml
- analytics-job-driver/pom.xml
- pom.xml
> Issue #TG-1177 feat: Upgrade to Java 11 in Analytics Core

- auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
- fix: perform pre_checks for to check for allowed tags
> SB-28788 fix: perform pre_checks for to check for allowed tags

- auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …
> SB-28788 feat: Auto Build Jenkins file update

- Jenkinsfile
- auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …
> SB-28788 -  Jenkins file update

- Jenkinsfile
- auto_build_deploy
> Java11 changes

- Jenkinsfile
- auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28788" title="SB-28788" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28788</a>  Upgrade Sunbird Ed data products to Java 11 for security vulnerability fixes
</td></table>
<br />
* Software …
> SB-28788 feat: Jenkins file update

- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/DruidDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/fetcher/TestDruidDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestDatasetUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28792" title="SB-28792" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28792</a>  Fix scientific notation numbers for DIKSHA landing page report metrics
</td></table>
<br />
* Software …
> Issue #SB-28792 feat: Fix scientific notation numbers for landing page report metrics

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/FrameworkContext.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/AzureDataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/CephS3DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/S3DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/storage/CustomS3StorageService.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
> SB-29641: Ceph object store support added

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/FrameworkContext.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/AzureDataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/CephS3DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/storage/CustomS3StorageService.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-29641" title="SB-29641" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-29641</a>  Functionality to fetch data from CephS3 storage
</td></table>
<br />
Added CephS3 object store support
* …
> SB-29641: Merge latest release-4.8.0 changes to 4.9.0

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
- analytics-job-driver/pom.xml
- pom.xml
This PR includes changes for upgrading Spark to version 3.0.1
All unit tests have been modified or fixed to run the existing code with Spark 3.0
> Issue SB-28788 feat: Upgrade spark to 3.0.0

- .circleci/config.yml
- analytics-core/pom.xml
- analytics-job-driver/pom.xml
- pom.xml
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28238" title="SB-28238" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28238</a>  Migrate to Java 11 for Sunbird Data Products
</td></table>
<br />
> Issue #SB-28238 feat: Upgrade to Java 11 in Analytics Core

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/FrameworkContext.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/DruidDataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/fetcher/TestDruidDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestCommonUtil.scala
- analytics-job-driver/pom.xml
- pom.xml
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28238" title="SB-28238" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28238</a>  Migrate to Java 11 for Sunbird Data Products
</td></table>
<br />
> Issue #SB-28238 feat: Update scruid scala version to 2.12

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/dispatcher/GcloudDispatcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/factory/DispatcherFactory.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/GcloudDataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/DatasetUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestOutputDispatcher.scala
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/OB-7" title="OB-7" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />OB-7</a>  Cloud storage SDK upgrade in Analytics Framework
</td></table>
<br />
> Issue #OB-7 feat: Cloud storage sdk upgrade in Analytics Framework

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/DataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/dispatcher/GcloudDispatcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/factory/DispatcherFactory.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/fetcher/GcloudDataFetcher.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/DatasetUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestDataFetcher.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/TestOutputDispatcher.scala
Issue #OB-7 feat: Cloud storage sdk upgrade in Analytics Framework
> Merge Release-5.0.0 to Release-5.1.0

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/JSONUtils.scala
> DD-2269 | Special characters issue fixes for sourcing metrics job

- .circleci/config.yml
- Jenkinsfile
- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CSPUtils.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestDatasetUtil.scala
- analytics-core/src/test/scala/org/ekstep/analytics/framework/util/TestRestUtil.scala
- auto_build_deploy
This change is related to CSP generalisation
1. Loading the cloud storage SDK as a Maven dependency
2. Created an interface to configure the spark CSP configuration
Ticket - https://project-sunbird.atlassian.net/browse/OB-525
> OB-525  CSP Changes

- .circleci/config.yml
> #0 fix: Fix CLOUD_STORE_VERSION parameter under circleci

- analytics-core/src/main/scala/org/ekstep/analytics/framework/FrameworkContext.scala
> #OB-553 fix: OCI key fixes for Spark jobs

- analytics-core/pom.xml
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CSPUtils.scala
- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/CommonUtil.scala
> WFS execution issue fixes

- analytics-core/src/main/scala/org/ekstep/analytics/framework/util/MergeUtil.scala
> fix: MergeUtil issue fixes for OCI
